replicaCount: 1

image:
  repository: ghcr.io/edward-forbes/task-manager-be
  tag: "93f73cf64938e93bff8d336fa1bbda9118b8cdb8"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: localhost
  path: /api
  pathType: Prefix