replicaCount: 1

image:
  repository: ghcr.io/edward-forbes/task-manager-be
  tag: "faa9b51db7b3148b2739801617fbebd123dde41c"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: localhost
  path: /api
  pathType: Prefix