image:
  registry: docker.io
  repository: bitnami/postgresql
  digest: sha256:40a261ed77f3b8dc65eeeec98bb79c4d3ef3410d7e2af7cfcf3785a6af00e4c5

auth:
  username: appuser
  database: appdb
  existingSecret: postgres-local-auth
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password

primary:
  persistence:
    enabled: true
    size: 1Gi