apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-local
  namespace: argocd

spec:
  project: local

  source:
    repoURL: https://github.com/edward-forbes/kubernetes-gitops.git
    targetRevision: main
    path: apps/ingress

    helm:
      valueFiles:
        - ../../environments/local/ingress-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true